[package]
name = "wilive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.82.1"
temporary = "0.6.4"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
